### ISSUE TITLE
optional image grid during annotation/ground truth/division line

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/scout#107]
## Feature description and context
Long standing issue of users getting lost in the image when processing large scale images. By adding a grid overlay option, we enable users to track their progress by referring to the grid as an additional reference point
Note: this feature becomes much more useful when paired with #53 

## Feature sign-off requirements
The following are true for annotation, ground truth, and division line pages
- toggle (off by default) labeled "grid"
- toggled can be clicked or activated with 'g'
- when on, grid toggle creates a grid overlay on the image
   - grid is 100x100 squares with excess in final row/column
   - grid lines extend from top to bottom and left to right
- toggle can trigger on and off
- grid displays responsively, showing the same grid regardless of zoom level ~statically, i.e., does not adjust with zoom~

**Comment by simbamangu** [comment]
From our side, confirmed:
* Toggle for grid
  * off by default
  * labelled 'grid'
  * Hotkey 'g'
* Grid overlay on image
  * Size user-customisable, default 5 wide x 3 tall (I don't think pixel widths appropriate but will ask the crew, would almost always leave uneven-sized set of cells along edges)
  * extend from top-to-bottom, left-to-right.
* Grid is static based on whole image, does not modify with zoom.

**Comment by TanyaStere42** [comment]
updated with hotkey requirement. sizing is something that will be variable between teams, so I'm going to go with something that will adjust well between different size images; we can always change it if we need to. Customization is a feature I will only consider with user feedback after implementation. 

Will get a design and mark this ready for development!
