### ISSUE TITLE
Cannot create overlapping bounding box annotations

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/scout#47]
**Current Behavior**
In Annotation and Ground Truth tasks, all bounding boxes must occupy distinct space
The 2nd bounding box cannot be drawn / completed if its 1st or 2nd point is within a previous bounding box OR touching the label text or any icons of a previous bounding box.

behavior should be managed at `/api/controllers/annotations.js`

**Expected Behavior**
Annotations can overlap

**QA Checklist**

- [ ] verify that a 2nd box can be completed when its end points intersect with any other bounding box, text or icons from previous drawing object.

Verify that a second annotation is drawn when there is an overlap of area
For annotation task:
- [ ] Draw annotation 1, draw annotation 2 without overlap (confirm current functionality)
- [ ] Draw annotation 1, draw annotation 2 with small overlap (less than half of area overlap)
- [ ] Draw annotation 1, draw annotation 2 with large overlap (more than half of area overlap)
- [ ] Draw annotation 1, draw annotation 2 with full overlap (entire area overlapping)

For ground truth task:
- [ ] Draw annotation 1, draw annotation 2 without overlap (confirm current functionality)
- [ ] Draw annotation 1, draw annotation 2 with small overlap (less than half of area overlap)
- [ ] Draw annotation 1, draw annotation 2 with large overlap (more than half of area overlap)
- [ ] Draw annotation 1, draw annotation 2 with full overlap (entire area overlapping)

**Comment by simbamangu** [comment]
Note that the label text box of the 1st box also blocks positioning of the 2nd box, not just the original bounding box.

**Comment by TanyaStere42** [comment]
@simbamangu can you verify QA requirements? And let me know if there's any additional detail I need to add

**Comment by TanyaStere42** [comment]
@simbamangu we're updating the requirements you suggested to no longer include "start on any point of canvas, other box, icon". Because there's event listeners, we either shut down all other functionality besides box-drawing, or we require annotations start in blank canvas space

**Comment by TanyaStere42** [comment]
@simbamangu Product verified, ready for QA. Click the boxes on the checklist and leave a comment with any notes as you finish
@erinz2020 Great job!

**Comment by erinz2020** [comment]
@TanyaStere42 Thank you for verification.
