### ISSUE TITLE
Export's "BOX H" in annotations reports wrong height

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/scout#48]
**Current Behavior**
`views/pages/exports.ejs`
BOX H field exports the image height

**Expected Behavior**
`views/pages/exports.ejs`
BOX H field exports the annotation height

**Comment by simbamangu** [comment]
Pull request made #51

Fixed two places in `app.js` where box.y was being assigned to Box H instead of box.h.

e.g. from

fields['Box H'] = typeof(box.h) !== 'undefined' ? box.y : ''; 

to

fields['Box H'] = typeof(box.h) !== 'undefined' ? box.h : '';
