### ISSUE TITLE
Zoom with scroll wheel

### ISSUE THREAD

**Issue by simbamangu** [WildMeOrg/scout#53]
Feature request for annotation: zoom with scroll wheel!

Expected behaviour:

Image zooms in/out at point under the cursor. Zoom level per click/roll should be user-selectable and default level fairly modest. At the moment the zoom icon zooms with factor 1.1:
`let newHeight = window.imageHeight / 1.1;
`
In map applications a factor of 1.41 (√2) works well, might be worth a try as default.

**Comment by TanyaStere42** [comment]
Request overall accepted. Configuration request "Zoom level per click/roll should be user-selectable" is being pulled out for a later development effort
