### ISSUE TITLE
Labels from models don't match default labels

### ISSUE THREAD

**Issue by simbamangu** [WildMeOrg/scout#70]
Problem: the v3-classifier can add new labels such as 'sable' or 'red lechwe' but those labels are rejected by the default label setting in the main window. 
![Screenshot from 2024-02-07 15-44-52](https://github.com/WildMeOrg/scout/assets/1159748/37bca0fc-9a24-44fb-8046-0cae9624754b)

Workaround: make sure you edit the 'labels' options to include red lechwe, sable and 'carcass' immediately after initial install. 

Add other missing labels in comments below.

**Comment by erinz2020** [comment]
Is there more tags that needs to be added besides sable and red lechwe?

**Comment by TanyaStere42** [comment]
We shouldn't need to know specific ones that need to be added. We want to move away from this manual addition method and start pulling the list from the models that are included

**Comment by erinz2020** [comment]
> We shouldn't need to know specific ones that need to be added. We want to move away from this manual addition method and start pulling the list from the models that are included

is there a json where we can get all the list? not sure who I should consult, currently the list is hardcoded

**Comment by TanyaStere42** [comment]
The list is something we get from scoutbot. I believe an annotation's individual classification is here: https://github.com/WildMeOrg/scoutbot/blob/493dbb7a335b4f650520cb3f195a3d2926b18eec/scoutbot/scoutbot.py#L118

Which means this may be something we need to get as a list from scoutbot, or we may need to assemble a list of the ones generated? @LashaO Is there a way to get a list of classifications (either all or used) from scoutbot to scout?

**Comment by TanyaStere42** [comment]
Talked with @erinz2020 , she says the 3-step method you described makes a lot of sense and wouldn't take a ton of refactor on our end. So if you can get a method together, we can get this solved :tada:

**Comment by LashaO** [comment]
Cool! I will slide it in sometime in this week's schedule if there is no rush. Let me know otherwise.

**Comment by TanyaStere42** [comment]
This week would mean we could get this resolved in this release, if you can?

**Comment by LashaO** [comment]
Got you. Scheduled dev time for tomorrow.

**Comment by TanyaStere42** [comment]
dependency on https://github.com/WildMeOrg/scoutbot/issues/22 per conversation above
