### ISSUE TITLE
Include GPS coordinates and date/time with image display (annotation and gallery interfaces)

### ISSUE THREAD

**Issue by holmbergius** [WildMeOrg/scout#80]
**Is your feature request related to a problem? Please describe.**
For anomaly detection, knowing the GPS coordinates and datetime of an image can help geo-reference the "where" and allow the user to take action outside of Scout. For example, known where a dead tree crown was detected by a Scout model can help send rangers to investigate the "why" and ensure they're looking at the right "when".

**Describe the solution you'd like**
However implemented, it would be helpful to allow users to see GPS coordinates and datetime associated with an image in front of them, both in the annotation interface and image gallery. To avoid bias during annotation, this might be implemented only at the Ground Truth stage (i.e. post-inference).

**Describe alternatives you've considered**
I am open to alternative ideas.

**Additional context**
Date-time referencing helps expand Scout into the monitoring domain, such as processing monthly batches of satellite data looking for poaching activity (e.g., elephant bones) or tree die-off.

**Comment by TanyaStere42** [comment]
gah, I wrote this up as part of a different ticket #83 . Gonna close this, but feel free to reopen if I'm missing a piece of this
